server:
  port: 9090
spring:
  datasource:
    username: root
    password: '123456'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hall?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  redis:
    port: 6379
    host: 127.0.0.1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: "secret" #密钥，jwt生成的密码
  client: "client" #客户Id，客户端的id
  provide_open: false #是否打开登录登出校验secret和client
upload:
  savePath: upload/
  httpPath: http://localhost:9090/files/get
quickboot:
  log_open: false
